---
abstract: 'App::TimeTracker Trello plugin'
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  Module::Build: '0.3601'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-TimeTracker-Command-Trello
requires:
  App::TimeTracker: '2.020'
  WWW::Trello::Lite: '0'
resources:
  homepage: http://timetracker.plix.at
  repository: git://github.com/domm/App-TimeTracker-Trello.git
version: '1.002'
